# =============================================================================
# Terra Viva - Docker Compose (Production Override)
# =============================================================================
# Usage:
#   docker compose -f compose.yaml -f compose.prod.yaml up -d
#
# This file overrides development settings for production deployment.
# Reference: https://docs.docker.com/compose/how-tos/production/
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # PostgreSQL Database (Production)
  # ---------------------------------------------------------------------------
  db:
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    # Remove healthcheck logging noise
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ---------------------------------------------------------------------------
  # Django Backend (Production)
  # ---------------------------------------------------------------------------
  backend:
    environment:
      - DEBUG=False
      - DJANGO_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - BASE_URL=${BASE_URL}
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-}
      - SUPABASE_STORAGE_BUCKET=${SUPABASE_STORAGE_BUCKET:-media}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY:-}
    # Remove source code mount for production
    volumes:
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    # Use gunicorn instead of runserver
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --access-logfile - --error-logfile -
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    # Structured logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # ---------------------------------------------------------------------------
  # Vue.js Frontend (Production)
  # ---------------------------------------------------------------------------
  frontend:
    build:
      args:
        VITE_API_URL: ${VITE_API_URL}
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
