# Generated by Django 4.2.17 on 2026-01-11 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
    ]
