# Generated by Django 5.2.10 on 2026-01-11 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_remove_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name_plural": "Categories"},
        ),
    ]
